### PR TITLE
Add TUI

### PR DESCRIPTION
**Pull request by bndabbs**

### CODE REVIEW

**Comment by dcode** [comment]
Can we run shell scripts through `shellcheck` or similar?

**Comment by jeffgeiger** [comment]
I do run my scripts through shellcheck. Outside of some slightly more esoteric quoting suggestions, it came out good.

**Comment by jeffgeiger** [comment]
Or, are you looking as an automated test?

**Comment by dcode** [comment]
Both? A recent [version](https://github.com/koalaman/shellcheck/commit/581bcc3907ab98e919a7dd60566810a928c46b95) of shellcheck supports a `.shellcheckrc`. If there are rules we have a good reason not to follow, we should disable them at the root of the dir and make sure the rest passes. I had a bunch of stuff come up on my homebrew version when I did
```
shellcheck bin/*
```

**Comment by dcode** [comment]
It'd be nice to have a standard to ensure future commits abide :dude:

**Comment by bndabbs** [comment]
I’d love to enable Travis-CI checks for all the repos. It’s be pretty
trivial to setup some auto lint checks and improve from there.

**Comment by jeffgeiger** [comment]
100% agrree with adding checks.
#FutureOps
#NotThisPR
#FileAnIssue

**Comment by dcode** [comment]
Right, the idea of my PR will allow us to run molecule checks, which covers yamllint, ansible-lint, eventually python lint (currently failing)...and we can run all that in concourse, plus deployment and idempotence check and testinfra checks. There's no coverage for shell scripts, but easy to add to the CI pipeline.

**Comment by jeffgeiger** [comment]
Again, great idea for an issue/future ops. Let's not bury the discussion in his PR.

**Pull request merged**
